source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

gem "devise", "1.2.1"
gem "devise_ldap_authenticatable", :path => "../../"

group :test do
  gem "ruby-debug19"
  gem "mocha"
  gem "shoulda"
  gem 'factory_girl_rails'
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "capybara"
  gem "launchy"
  gem "autotest-rails"
  gem "ZenTest"
  #gem "redgreen" # https://rails.lighthouseapp.com/projects/8994/tickets/5541-autotest-fail-with-rails-300-and-ruby-192p0-2010-08-18-revision-29036-x86_64-darwin1040
  gem "autotest-growl"
end
