source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3-ruby', :require => 'sqlite3'

gem "devise", "1.2.1"
gem "system_timer", :platforms => :mri_18
gem "devise_ldap_authenticatable", :path => "../../"

group :test do
  gem "ruby-debug", :platforms => :mri_18
  gem "ruby-debug19", :platforms => :mri_19
  gem "mocha"
  gem "shoulda"
  gem 'factory_girl_rails'
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "capybara"
  gem "launchy"
  gem "autotest-rails"
  gem "ZenTest"
  gem "redgreen", :platforms => :mri_18
  gem "autotest-growl"
end
